### ISSUE TITLE
ImportError: No module named 'services' (in Python 3)

### ISSUE THREAD

**Issue by iamale** [blockstack/pybitcoin#56]
```
Python 3.5.2 (default, Jul 17 2016, 00:00:00) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pybitcoin import LitecoinPrivateKey
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<...>/site-packages/pybitcoin/__init__.py", line 10, in <module>
    import services
ImportError: No module named 'services'
```

See: https://www.python.org/dev/peps/pep-0328/#rationale-for-absolute-imports

**Comment by iamale** [comment]
I tested briefly and some other py3k-related errors popped up. Any plans to introduce Python 3 support?

**Comment by venil7** [comment]
I'm getting the same issue, my Python version
```
Python 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:04:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
```

also this package unavailable for install thru `conda`

**Comment by lephleg** [comment]
Same error. Python version:
```
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by n644dc** [comment]
any change at getting Python3 support?

**Comment by FinlayDaG33k** [comment]
Doesn't seem like there has been any change...
