### ISSUE TITLE
"services" not found

### ISSUE THREAD

**Issue by GildedHonour** [blockstack/pybitcoin#62]
```
>>> from pybitcoin import BitcoinPrivateKey
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/.local/lib/python3.6/site-packages/pybitcoin/__init__.py", line 10, in <module>
    import services
ModuleNotFoundError: No module named 'services'
>>> from pybitcoin import BitcoinPrivateKey
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/.local/lib/python3.6/site-packages/pybitcoin/__init__.py", line 10, in <module>
    import services
ModuleNotFoundError: No module named 'services'

```

**Comment by GildedHonour** [comment]
```
$ pip3.6 install --user services
Collecting services
  Could not find a version that satisfies the requirement services (from versions: )
No matching distribution found for services

```

**Comment by teran-mckinney** [comment]
This doesn't work with Python 3: #56 

Try with Python 2. "services" is a local import, pip installing it won't do you any good.
