### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by quinnoaj** [blockstack/pybitcoin#65]
When I run 

`python unit_tests.py` I got the following error:

`Traceback (most recent call last):
 File "unit_tests.py", line 38, in <module>
   from settings import BITCOIND_RPC_PASSWORD, BITCOIND_RPC_USERNAME, \ ImportError: cannot import name BITCOIND_RPC_PASSWORD`

I looked into the scripts and it seems fine, how to fix this error? Thank you.

**Comment by quinnoaj** [comment]
also in `python wallet.py` I got the following error:

`Traceback (most recent call last):
   File "wallet.py", line 12,, in <module>
     from .keypair import * 
ValueError: Attempted relative import in non-package`
